{% set name = "ammonite-repl" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/com-lihaoyi/Ammonite
  git_rev: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - curl
    - findutils
    - maven
    - openjdk =17
  run:
    - openjdk =17

test:
  commands:
    - amm --help

about:
  home: https://github.com/com-lihaoyi/Ammonite
  license: MIT
  license_file: 
    - LICENSE
    - target/generated-resources/licenses/
  summary: Scala Scripting
  dev_url: https://github.com/com-lihaoyi/Ammonite

extra:
  recipe-maintainers:
    - danielnachun
